PR_TITLE_REGEX: /[a-z][a-z]/i
COMMIT_MESSAGE_REGEX: /(#)(#)((?:[a-z][a-z]+))(\d{3})(:)([a-z0-9])/i
OUTPUT_TITLE_FAIL: Pull request validation failed.
OUTPUT_TITLE_SUCCESS: Pull request validation success.